# Generated by Django 5.2.6 on 2026-01-26 01:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='travel_committees/logos/')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_committees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Travel Committee',
                'verbose_name_plural': 'Travel Committees',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TravelDealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_type', models.CharField(choices=[('flat', 'Flat'), ('percentage', 'Percentage')], default='percentage', max_length=20)),
                ('commission_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_dealers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Travel Dealer',
                'verbose_name_plural': 'Travel Dealers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TravelAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_type', models.CharField(choices=[('flat', 'Flat'), ('percentage', 'Percentage')], default='percentage', max_length=20)),
                ('commission_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_agents', to=settings.AUTH_USER_MODEL)),
                ('committees', models.ManyToManyField(blank=True, related_name='agents', to='travel.travelcommittee')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='travel.traveldealer')),
            ],
            options={
                'verbose_name': 'Travel Agent',
                'verbose_name_plural': 'Travel Agents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TravelVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('vehicle_no', models.CharField(max_length=50, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='travel_vehicles/')),
                ('is_active', models.BooleanField(default=True)),
                ('departure_time', models.TimeField()),
                ('actual_seat_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('seat_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='travel.travelcommittee')),
                ('from_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles_from', to='shared.place')),
                ('to_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles_to', to='shared.place')),
            ],
            options={
                'verbose_name': 'Travel Vehicle',
                'verbose_name_plural': 'Travel Vehicles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TravelVehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='travel_vehicles/images/')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='travel.travelvehicle')),
            ],
            options={
                'verbose_name': 'Travel Vehicle Image',
                'verbose_name_plural': 'Travel Vehicle Images',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TravelVehicleSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('boarded', 'Boarded')], default='available', max_length=20)),
                ('floor', models.CharField(choices=[('upper', 'Upper'), ('lower', 'Lower')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='travel.travelvehicle')),
            ],
            options={
                'verbose_name': 'Travel Vehicle Seat',
                'verbose_name_plural': 'Travel Vehicle Seats',
                'ordering': ['vehicle', 'floor', 'side', 'number'],
                'unique_together': {('vehicle', 'side', 'number', 'floor')},
            },
        ),
        migrations.CreateModel(
            name='TravelCommitteeStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_permission', models.BooleanField(default=False)),
                ('boarding_permission', models.BooleanField(default=False)),
                ('finance_permission', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('travel_committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='travel.travelcommittee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_committee_staff', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Travel Committee Staff',
                'verbose_name_plural': 'Travel Committee Staff',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'travel_committee')},
            },
        ),
        migrations.CreateModel(
            name='TravelBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('booked', 'Booked'), ('boarded', 'Boarded')], default='pending', max_length=20)),
                ('booking_date', models.DateTimeField()),
                ('boarding_date', models.DateTimeField(blank=True, null=True)),
                ('actual_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('dealer_commission', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('agent_commission', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('system_commission', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='travel.travelagent')),
                ('boarding_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='shared.place')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_bookings', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='travel.travelvehicle')),
                ('vehicle_seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='travel.travelvehicleseat')),
            ],
            options={
                'verbose_name': 'Travel Booking',
                'verbose_name_plural': 'Travel Bookings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ticket_number'], name='travel_trav_ticket__5500e4_idx'), models.Index(fields=['status', '-created_at'], name='travel_trav_status_d77a6c_idx')],
            },
        ),
    ]
