# Generated by Django 5.2.6 on 2026-01-27 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_agent'),
        ('travel', '0002_remove_travelvehicleseat_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelbooking',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='core.agent'),
        ),
        migrations.DeleteModel(
            name='TravelAgent',
        ),
    ]
