# Generated by Django 5.2.6 on 2026-01-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_alter_travelbooking_agent_delete_travelagent'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelbooking',
            name='qr_code',
            field=models.TextField(blank=True, help_text='QR code data for ticket scanning', null=True),
        ),
    ]
