# Generated by Django 5.2.6 on 2026-01-26 01:52

import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_commission', models.DecimalField(decimal_places=2, default=0, help_text='Sales commission percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('shipping_charge_commission', models.IntegerField(default=10, help_text='Shipping charge commission percentage (added to courier rates)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('travel_ticket_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Travel ticket commission percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('balance', models.DecimalField(decimal_places=2, default=0, help_text='Platform balance', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('merchant_agreement_file', models.FileField(blank=True, help_text='Merchant agreement file for download', null=True, upload_to='merchant_agreements/')),
                ('is_phone_pe', models.BooleanField(default=True, help_text='Enable PhonePe payment method')),
                ('is_sabpaisa', models.BooleanField(default=True, help_text='Enable SabPaisa payment method')),
                ('is_cod', models.BooleanField(default=True, help_text='Enable Cash on Delivery payment method')),
                ('is_razorpay', models.BooleanField(default=True, help_text='Enable Razorpay payment method')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Super Setting',
                'verbose_name_plural': 'Super Settings',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('commission', 'Commission'), ('commission_deduction', 'Commission Deduction'), ('shipping_charge_deduction', 'Shipping Charge Deduction'), ('withdrawal', 'Withdrawal Request'), ('withdrawal_processed', 'Withdrawal Processed'), ('phonepe_payment', 'PhonePe Payment'), ('sabpaisa_payment', 'SabPaisa Payment'), ('razorpay_payment', 'Razorpay Payment'), ('payout', 'Merchant Payout')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount (can be negative for deductions)', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Transaction description')),
                ('merchant_order_id', models.CharField(blank=True, db_index=True, help_text='Merchant Order ID for PhonePe/SabPaisa payment callbacks (clientTxnId for SabPaisa)', max_length=100, null=True)),
                ('utr', models.CharField(blank=True, help_text='Unique Transaction Reference (UTR) for PhonePe transactions', max_length=100, null=True)),
                ('bank_id', models.CharField(blank=True, help_text='Bank ID for PhonePe transactions', max_length=20, null=True)),
                ('vpa', models.CharField(blank=True, help_text='Virtual Payment Address (VPA) for PhonePe transactions', max_length=100, null=True)),
                ('payer_name', models.CharField(blank=True, help_text='Name of the payer/account holder for this transaction', max_length=200, null=True)),
                ('wallet_before', models.DecimalField(blank=True, decimal_places=2, help_text='Wallet balance before this transaction', max_digits=10, null=True)),
                ('wallet_after', models.DecimalField(blank=True, decimal_places=2, help_text='Wallet balance after this transaction', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method_type', models.CharField(choices=[('bank_account', 'Bank Account'), ('upi', 'UPI'), ('wallet', 'Wallet')], help_text='Type of payment method', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Verification status', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if status is rejected', null=True)),
                ('payment_details', models.JSONField(default=dict, help_text='Payment method details (varies by payment_method_type)')),
                ('approved_at', models.DateTimeField(blank=True, help_text='When payment method was approved', null=True)),
                ('rejected_at', models.DateTimeField(blank=True, help_text='When payment method was rejected', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Payment Method',
                'verbose_name_plural': 'User Payment Methods',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if status is rejected', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('country_code', models.CharField(choices=[('+977', '+977'), ('+91', '+91')], default='+91', max_length=5)),
                ('country', models.CharField(choices=[('Nepal', 'Nepal'), ('India', 'India')], default='India', max_length=10)),
                ('fcm_token', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('national_id', models.CharField(blank=True, help_text='National ID number', max_length=50, null=True)),
                ('national_id_document_front', models.ImageField(blank=True, help_text='National ID document front image', null=True, upload_to='kyc_documents/')),
                ('national_id_document_back', models.ImageField(blank=True, help_text='National ID document back image', null=True, upload_to='kyc_documents/')),
                ('pan_no', models.CharField(blank=True, help_text='PAN (Permanent Account Number)', max_length=20, null=True)),
                ('pan_document', models.ImageField(blank=True, help_text='PAN document image', null=True, upload_to='kyc_documents/')),
                ('company_register_id', models.CharField(blank=True, help_text='Company registration ID (for merchants only)', max_length=50, null=True)),
                ('company_register_document', models.ImageField(blank=True, help_text='Company registration document (for merchants only)', null=True, upload_to='kyc_documents/')),
                ('merchant_agreement', models.FileField(blank=True, help_text='Signed merchant agreement PDF document (for merchants only)', null=True, upload_to='kyc_documents/')),
                ('is_kyc_verified', models.BooleanField(default=False, help_text='Whether KYC has been verified by admin')),
                ('kyc_submitted_at', models.DateTimeField(blank=True, help_text='When user submitted KYC information', null=True)),
                ('kyc_verified_at', models.DateTimeField(blank=True, help_text='When KYC was verified by admin', null=True)),
                ('kyc_rejected_at', models.DateTimeField(blank=True, help_text='When KYC was rejected by admin', null=True)),
                ('kyc_rejection_reason', models.TextField(blank=True, help_text='Reason for KYC rejection', null=True)),
                ('is_merchant', models.BooleanField(default=False, help_text='Whether user is a merchant/seller')),
                ('is_driver', models.BooleanField(default=False, help_text='Whether user is a driver')),
                ('balance', models.DecimalField(decimal_places=2, default=0, help_text='User balance', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_freeze', models.BooleanField(default=False, help_text='Whether user account is frozen')),
                ('merchant_code', models.CharField(blank=True, help_text='Auto-generated merchant code (e.g., MSB1, MSB2) - only for merchants', max_length=50, null=True, unique=True)),
                ('is_edit_access', models.BooleanField(default=False, help_text='Whether merchant can edit store after creation (default False)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('building_name', models.CharField(blank=True, max_length=100, null=True)),
                ('flat_no', models.CharField(blank=True, max_length=50, null=True)),
                ('landmark', models.CharField(blank=True, max_length=200, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=12, max_digits=20, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=12, max_digits=20, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('order', 'Order'), ('promotion', 'Promotion'), ('security', 'Security'), ('general', 'General')], default='general', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('otp', models.CharField(max_length=6)),
                ('country_code', models.CharField(choices=[('+977', '+977'), ('+91', '+91')], max_length=5)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone'], name='core_otp_phone_291d4c_idx')],
            },
        ),
    ]
