# Generated by Django 5.2.6 on 2026-01-26 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='related_order',
            field=models.ForeignKey(blank=True, help_text='Related order for commission/payout/phonepe transactions', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='ecommerce.order'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userpaymentmethod',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_method', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='merchant',
            field=models.ForeignKey(limit_choices_to={'is_merchant': True}, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='payment_method',
            field=models.ForeignKey(blank=True, help_text='Payment method used for this withdrawal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawals', to='core.userpaymentmethod'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='related_withdrawal',
            field=models.ForeignKey(blank=True, help_text='Related withdrawal for withdrawal transactions', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='core.withdrawal'),
        ),
        migrations.AddIndex(
            model_name='userpaymentmethod',
            index=models.Index(fields=['user'], name='core_userpa_user_id_9e6d5e_idx'),
        ),
        migrations.AddIndex(
            model_name='userpaymentmethod',
            index=models.Index(fields=['status', '-created_at'], name='core_userpa_status_d3fedf_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawal',
            index=models.Index(fields=['merchant', '-created_at'], name='core_withdr_merchan_2e9750_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawal',
            index=models.Index(fields=['status', '-created_at'], name='core_withdr_status_c136f7_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', '-created_at'], name='core_transa_user_id_1afe97_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type', '-created_at'], name='core_transa_transac_f8df1d_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['merchant_order_id'], name='core_transa_merchan_0c5f34_idx'),
        ),
    ]
