# Generated by Django 5.2.5 on 2025-11-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_address_latitude_address_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_kyc_verified',
            field=models.BooleanField(default=False, help_text='Whether KYC has been verified by admin'),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_submitted_at',
            field=models.DateTimeField(blank=True, help_text='When user submitted KYC information', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_verified_at',
            field=models.DateTimeField(blank=True, help_text='When KYC was verified by admin', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='national_id',
            field=models.CharField(blank=True, help_text='National ID number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='national_id_document',
            field=models.ImageField(blank=True, help_text='National ID document image', null=True, upload_to='kyc_documents/'),
        ),
    ]
