# Generated by Django 5.2.5 on 2025-11-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_is_kyc_verified_user_kyc_submitted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pan_document',
            field=models.ImageField(blank=True, help_text='PAN document image', null=True, upload_to='kyc_documents/'),
        ),
        migrations.AddField(
            model_name='user',
            name='pan_no',
            field=models.CharField(blank=True, help_text='PAN (Permanent Account Number)', max_length=20, null=True),
        ),
    ]
