# Generated by Django 5.2.6 on 2026-01-27 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_agent'),
        ('travel', '0004_travelbooking_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='related_travel_booking',
            field=models.ForeignKey(blank=True, help_text='Related travel booking for travel transactions', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='travel.travelbooking'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('commission', 'Commission'), ('commission_deduction', 'Commission Deduction'), ('shipping_charge_deduction', 'Shipping Charge Deduction'), ('withdrawal', 'Withdrawal Request'), ('withdrawal_processed', 'Withdrawal Processed'), ('phonepe_payment', 'PhonePe Payment'), ('sabpaisa_payment', 'SabPaisa Payment'), ('razorpay_payment', 'Razorpay Payment'), ('payout', 'Merchant Payout'), ('travel_booking_revenue', 'Travel Booking Revenue'), ('travel_booking_commission', 'Travel Booking Commission')], max_length=30),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL),
        ),
    ]
