# Generated by Django 5.2.5 on 2025-11-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_pan_document_user_pan_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kyc_rejected_at',
            field=models.DateTimeField(blank=True, help_text='When KYC was rejected by admin', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for KYC rejection', null=True),
        ),
    ]
