# Generated by Django 5.2.5 on 2025-11-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_kyc_rejection_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(choices=[('Nepal', 'Nepal'), ('India', 'India')], default='India', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='country_code',
            field=models.CharField(choices=[('+977', '+977'), ('+91', '+91')], default='+91', max_length=5),
        ),
    ]
