# Generated by Django 5.2.6 on 2025-12-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_country_alter_user_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_driver',
            field=models.BooleanField(default=False, help_text='Whether user is a driver'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_merchant',
            field=models.BooleanField(default=False, help_text='Whether user is a merchant/seller'),
        ),
    ]
