# Generated by Django 5.2.6 on 2025-12-18 07:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_is_driver_user_is_merchant'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_commission', models.DecimalField(decimal_places=2, default=0, help_text='Sales commission percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('basic_shipping_charge', models.DecimalField(decimal_places=2, default=0, help_text='Basic shipping charge per vendor', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('balance', models.DecimalField(decimal_places=2, default=0, help_text='Platform balance', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Super Setting',
                'verbose_name_plural': 'Super Settings',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='User balance', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
