# Generated by Django 5.2.6 on 2025-12-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_supersetting_user_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='national_id_document',
        ),
        migrations.AddField(
            model_name='user',
            name='company_register_document',
            field=models.ImageField(blank=True, help_text='Company registration document (for merchants only)', null=True, upload_to='kyc_documents/'),
        ),
        migrations.AddField(
            model_name='user',
            name='company_register_id',
            field=models.CharField(blank=True, help_text='Company registration ID (for merchants only)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='national_id_document_back',
            field=models.ImageField(blank=True, help_text='National ID document back image', null=True, upload_to='kyc_documents/'),
        ),
        migrations.AddField(
            model_name='user',
            name='national_id_document_front',
            field=models.ImageField(blank=True, help_text='National ID document front image', null=True, upload_to='kyc_documents/'),
        ),
    ]
