# Generated by Django 5.2.6 on 2025-12-27 08:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_user_national_id_document_and_more'),
        ('ecommerce', '0019_remove_order_phonepe_bank_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('commission', 'Commission'), ('withdrawal', 'Withdrawal Request'), ('withdrawal_processed', 'Withdrawal Processed'), ('phonepe_payment', 'PhonePe Payment'), ('payout', 'Merchant Payout')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Transaction description')),
                ('merchant_order_id', models.CharField(blank=True, db_index=True, help_text='Merchant Order ID for PhonePe payment callbacks', max_length=100, null=True)),
                ('utr', models.CharField(blank=True, help_text='Unique Transaction Reference (UTR) for PhonePe transactions', max_length=100, null=True)),
                ('bank_id', models.CharField(blank=True, help_text='Bank ID for PhonePe transactions', max_length=20, null=True)),
                ('vpa', models.CharField(blank=True, help_text='Virtual Payment Address (VPA) for PhonePe transactions', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_order', models.ForeignKey(blank=True, help_text='Related order for commission/payout/phonepe transactions', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='ecommerce.order')),
                ('related_withdrawal', models.ForeignKey(blank=True, help_text='Related withdrawal for withdrawal transactions', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='ecommerce.withdrawal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='core_transa_user_id_1afe97_idx'), models.Index(fields=['transaction_type', '-created_at'], name='core_transa_transac_f8df1d_idx'), models.Index(fields=['merchant_order_id'], name='core_transa_merchan_0c5f34_idx')],
            },
        ),
    ]
