# Generated by Django 5.2.6 on 2025-12-28 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_address_building_name_address_flat_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_freeze',
            field=models.BooleanField(default=False, help_text='Whether user account is frozen'),
        ),
    ]
