# Generated by Django 5.2.6 on 2025-12-28 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_user_is_freeze'),
    ]

    operations = [
        migrations.AddField(
            model_name='supersetting',
            name='merchant_agreement_file',
            field=models.FileField(blank=True, help_text='Merchant agreement file for download', null=True, upload_to='merchant_agreements/'),
        ),
        migrations.AddField(
            model_name='user',
            name='merchant_agreement',
            field=models.ImageField(blank=True, help_text='Signed merchant agreement document (for merchants only)', null=True, upload_to='kyc_documents/'),
        ),
    ]
