# Generated by Django 5.2.6 on 2025-12-28 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_supersetting_merchant_agreement_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='merchant_agreement',
            field=models.FileField(blank=True, help_text='Signed merchant agreement PDF document (for merchants only)', null=True, upload_to='kyc_documents/'),
        ),
    ]
