# Generated by Django 5.2.6 on 2025-12-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_user_merchant_agreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='merchant_code',
            field=models.CharField(blank=True, help_text='Auto-generated merchant code (e.g., MSB1, MSB2) - only for merchants', max_length=50, null=True, unique=True),
        ),
    ]
