# Generated by Django migration

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_generate_merchant_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payer_name',
            field=models.CharField(blank=True, help_text='Name of the payer/account holder for this transaction', max_length=200, null=True),
        ),
    ]

