# Generated by Django migration

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_transaction_payer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('commission', 'Commission'), ('withdrawal', 'Withdrawal Request'), ('withdrawal_processed', 'Withdrawal Processed'), ('phonepe_payment', 'PhonePe Payment'), ('sabpaisa_payment', 'SabPaisa Payment'), ('payout', 'Merchant Payout')], max_length=30),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='merchant_order_id',
            field=models.CharField(blank=True, db_index=True, help_text='Merchant Order ID for PhonePe/SabPaisa payment callbacks (clientTxnId for SabPaisa)', max_length=100, null=True),
        ),
    ]
