# Generated by Django 5.2.6 on 2026-01-25 09:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def clear_orphaned_withdrawal_references(apps, schema_editor):
    """
    Clear orphaned related_withdrawal_id values before changing the foreign key
    to point to the new core.Withdrawal model. Old references point to ecommerce.Withdrawal
    which will be deleted, so we need to set them to NULL.
    """
    # Set all related_withdrawal_id to NULL since we're moving from ecommerce.Withdrawal to core.Withdrawal
    # Use raw SQL to avoid issues with the foreign key relationship during migration
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "UPDATE core_transaction SET related_withdrawal_id = NULL WHERE related_withdrawal_id IS NOT NULL"
        )


def reverse_clear_orphaned_withdrawal_references(apps, schema_editor):
    """
    Reverse migration - nothing to do as we can't restore the old references
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_add_deduction_transaction_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='supersetting',
            name='travel_ticket_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Travel ticket commission percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.CreateModel(
            name='UserPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method_type', models.CharField(choices=[('bank_account', 'Bank Account'), ('upi', 'UPI'), ('wallet', 'Wallet')], help_text='Type of payment method', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Verification status', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if status is rejected', null=True)),
                ('payment_details', models.JSONField(default=dict, help_text='Payment method details (varies by payment_method_type)')),
                ('approved_at', models.DateTimeField(blank=True, help_text='When payment method was approved', null=True)),
                ('rejected_at', models.DateTimeField(blank=True, help_text='When payment method was rejected', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_method', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Payment Method',
                'verbose_name_plural': 'User Payment Methods',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if status is rejected', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(limit_choices_to={'is_merchant': True}, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL)),
                ('payment_method', models.ForeignKey(blank=True, help_text='Payment method used for this withdrawal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawals', to='core.userpaymentmethod')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        # Clear orphaned withdrawal references before changing the foreign key
        migrations.RunPython(
            clear_orphaned_withdrawal_references,
            reverse_clear_orphaned_withdrawal_references,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='related_withdrawal',
            field=models.ForeignKey(blank=True, help_text='Related withdrawal for withdrawal transactions', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='core.withdrawal'),
        ),
        migrations.AddIndex(
            model_name='userpaymentmethod',
            index=models.Index(fields=['user'], name='core_userpa_user_id_9e6d5e_idx'),
        ),
        migrations.AddIndex(
            model_name='userpaymentmethod',
            index=models.Index(fields=['status', '-created_at'], name='core_userpa_status_d3fedf_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawal',
            index=models.Index(fields=['merchant', '-created_at'], name='core_withdr_merchan_2e9750_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawal',
            index=models.Index(fields=['status', '-created_at'], name='core_withdr_status_c136f7_idx'),
        ),
    ]
