# Generated by Django 5.2.6 on 2026-01-26 01:52

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CMSPages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Page title', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of title', max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, help_text='Page image', null=True, upload_to='website/cms/')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Page content')),
                ('on_footer', models.BooleanField(default=False, help_text='Show in footer links')),
                ('on_menu', models.BooleanField(default=False, help_text='Show in main navigation menu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CMS Page',
                'verbose_name_plural': 'CMS Pages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Company/Website name', max_length=200)),
                ('phone', models.CharField(help_text='Contact phone number', max_length=20)),
                ('email', models.EmailField(help_text='Contact email address', max_length=254)),
                ('address', models.TextField(blank=True, help_text='Company address')),
                ('website', models.URLField(blank=True, help_text='Company website URL')),
                ('logo', models.ImageField(blank=True, help_text='Company logo', null=True, upload_to='website/logos/')),
                ('tagline', models.CharField(blank=True, help_text='Website tagline', max_length=300)),
                ('hero_title', models.CharField(help_text='Hero section main title', max_length=200)),
                ('hero_image', models.ImageField(blank=True, help_text='Hero section background image', null=True, upload_to='website/hero/')),
                ('hero_description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Hero section description')),
                ('about_title', models.CharField(help_text='About section title', max_length=200)),
                ('about_tag', models.CharField(blank=True, help_text='About section tagline', max_length=200)),
                ('about_image', models.ImageField(blank=True, help_text='About section image', null=True, upload_to='website/about/')),
                ('about_description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='About section description')),
                ('total_customers', models.IntegerField(default=0, help_text='Total number of customers')),
                ('total_daily_signup', models.IntegerField(default=0, help_text='Daily signup count')),
                ('total_txn_everyday', models.IntegerField(default=0, help_text='Daily transaction count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Website Settings',
                'verbose_name_plural': 'Website Settings',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Service title', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of title', max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, help_text='Service image', null=True, upload_to='website/services/')),
                ('description', models.TextField(help_text='Service description')),
                ('url', models.URLField(blank=True, help_text='Service URL for redirect', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['created_at'],
            },
        ),
    ]
