# Generated by Django 5.2.5 on 2025-10-21 13:33

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmspages',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Page content'),
        ),
    ]
