# Generated by Django 5.2.5 on 2025-10-21 13:35

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_cmspages_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysetting',
            name='about_description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='About section description'),
        ),
        migrations.AlterField(
            model_name='mysetting',
            name='hero_description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Hero section description'),
        ),
    ]
