# Generated by Django 5.2.5 on 2025-11-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_mysetting_about_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysetting',
            name='address',
            field=models.TextField(blank=True, help_text='Company address'),
        ),
        migrations.AddField(
            model_name='mysetting',
            name='website',
            field=models.URLField(blank=True, help_text='Company website URL'),
        ),
    ]
