# Generated by Django 5.2.5 on 2025-11-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_mysetting_address_mysetting_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='url',
            field=models.URLField(blank=True, help_text='Service URL for redirect', null=True),
        ),
    ]
