# Generated by Django 5.2.6 on 2026-01-26 01:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('minimum_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GlobalCourier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier_id', models.IntegerField(help_text='Shipdaak courier ID', unique=True)),
                ('courier_name', models.CharField(help_text='Courier name', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this courier is active globally')),
                ('priority', models.IntegerField(default=0, help_text='Priority order (lower = higher priority)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Global Courier',
                'verbose_name_plural': 'Global Couriers',
                'ordering': ['priority', 'courier_name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='ecommerce.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, help_text="Subtotal for this vendor's products", max_digits=10)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, help_text='Shipping cost for this order', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('payment_method', models.CharField(choices=[('cod', 'Cash on Delivery'), ('online', 'Online Payment'), ('phonepe', 'PhonePe Payment'), ('razorpay', 'Razorpay Payment')], default='cod', max_length=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('merchant_ready_date', models.DateTimeField(blank=True, help_text='When merchant accepts and marks ready', null=True)),
                ('pickup_date', models.DateTimeField(blank=True, help_text='When order is picked up', null=True)),
                ('delivered_date', models.DateTimeField(blank=True, help_text='When order is delivered', null=True)),
                ('reject_reason', models.TextField(blank=True, help_text='Reason if merchant rejects', null=True)),
                ('shipdaak_awb_number', models.CharField(blank=True, help_text='Shipdaak AWB/Tracking number', max_length=50, null=True)),
                ('shipdaak_shipment_id', models.IntegerField(blank=True, help_text='Shipdaak shipment ID', null=True)),
                ('shipdaak_order_id', models.IntegerField(blank=True, help_text='Shipdaak order ID', null=True)),
                ('shipdaak_label_url', models.URLField(blank=True, help_text='Shipdaak shipping label URL', null=True)),
                ('shipdaak_manifest_url', models.URLField(blank=True, help_text='Shipdaak manifest URL', null=True)),
                ('shipdaak_status', models.CharField(blank=True, help_text='Current Shipdaak shipment status', max_length=50, null=True)),
                ('shipdaak_courier_id', models.IntegerField(blank=True, help_text='Shipdaak courier ID used for shipment', null=True)),
                ('shipdaak_courier_name', models.CharField(blank=True, help_text='Shipdaak courier name', max_length=100, null=True)),
                ('package_length', models.DecimalField(blank=True, decimal_places=2, help_text='Package length in cm', max_digits=8, null=True)),
                ('package_breadth', models.DecimalField(blank=True, decimal_places=2, help_text='Package breadth in cm', max_digits=8, null=True)),
                ('package_height', models.DecimalField(blank=True, decimal_places=2, help_text='Package height in cm', max_digits=8, null=True)),
                ('package_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Package weight in grams', max_digits=8, null=True)),
                ('commission_processed', models.BooleanField(default=False, help_text='Whether commission has been processed for this order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing_address', models.ForeignKey(blank=True, help_text='Billing address for this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_orders', to='core.address')),
                ('shipping_address', models.ForeignKey(blank=True, help_text='Shipping address for this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_orders', to='core.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('actual_price', models.DecimalField(blank=True, decimal_places=2, help_text='Merchant price before commission', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.DecimalField(decimal_places=2, help_text='Selling price with commission applied', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_type', models.CharField(blank=True, choices=[('flat', 'Flat'), ('percentage', 'Percentage')], max_length=10, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False, help_text='Product must be approved by admin before it appears in app/web')),
                ('variants', models.JSONField(blank=True, default=dict, help_text='Product variant data with enabled, variants, and combinations')),
                ('item_code', models.CharField(blank=True, help_text='Auto-generated product code (e.g., PSB1, PSB2)', max_length=50, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='ecommerce.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Popup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Popup image', upload_to='popups/')),
                ('title', models.CharField(help_text='Popup title', max_length=200)),
                ('url', models.URLField(blank=True, help_text='URL to navigate when popup is clicked (ignored if product is selected)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this popup is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, help_text='Product to navigate to when popup is clicked (takes priority over URL)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='popups', to='ecommerce.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Banner image', upload_to='banners/')),
                ('title', models.CharField(help_text='Banner title', max_length=200)),
                ('url', models.URLField(blank=True, help_text='URL to navigate when banner is clicked (ignored if product is selected)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this banner is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, help_text='Product to navigate to when banner is clicked (takes priority over URL)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='ecommerce.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ecommerce.product')),
            ],
            options={
                'ordering': ['is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='store_logos/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='store_banners/')),
                ('address', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=12, max_digits=20, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=12, max_digits=20, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_opened', models.BooleanField(default=True, help_text='Whether the store is open for business. Only admins can change this.')),
                ('minimum_order_value', models.DecimalField(decimal_places=2, default=0, help_text='Minimum order value required for this store', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipdaak_pickup_warehouse_id', models.IntegerField(blank=True, help_text='Shipdaak pickup warehouse ID', null=True)),
                ('shipdaak_rto_warehouse_id', models.IntegerField(blank=True, help_text='Shipdaak RTO warehouse ID', null=True)),
                ('shipdaak_warehouse_created_at', models.DateTimeField(blank=True, help_text='When warehouse was created in Shipdaak', null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShippingChargeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_charge', models.DecimalField(decimal_places=2, help_text='Shipping charge amount (courier_rate + commission)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('courier_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Base courier rate', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('commission', models.DecimalField(blank=True, decimal_places=2, help_text='Shipping charge commission amount', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('paid_by', models.CharField(choices=[('merchant', 'Merchant'), ('customer', 'Customer')], default='merchant', help_text='Who paid the shipping charge', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_charge_history', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_charge_history', to='ecommerce.order')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_charge_history', to='ecommerce.store')),
            ],
            options={
                'verbose_name': 'Shipping Charge History',
                'verbose_name_plural': 'Shipping Charge Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='ecommerce.store'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actual_price', models.DecimalField(blank=True, decimal_places=2, help_text='Merchant price before commission at time of order', max_digits=10, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_variant', models.CharField(blank=True, help_text='Selected product variant (e.g., "Size:Small,Color:Red")', max_length=255, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ecommerce.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.store')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='merchant',
            field=models.ForeignKey(blank=True, help_text='Store/vendor for this order', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='ecommerce.store'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.product')),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('comment', models.TextField()),
                ('is_verified_purchase', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='ecommerce.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'product')},
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'product')},
            },
        ),
    ]
