# Generated by Django 5.2.6 on 2025-11-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_order_payment_method_order_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phonepe_bank_id',
            field=models.CharField(blank=True, help_text='Bank ID (e.g., SBIN)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='phonepe_card_network',
            field=models.CharField(blank=True, help_text='Card Network (e.g., UNKNOWN)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='phonepe_instrument_type',
            field=models.CharField(blank=True, help_text='Instrument Type (e.g., UPI)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='phonepe_order_id',
            field=models.CharField(blank=True, help_text='PhonePe Order ID (OMO...)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='phonepe_payment_mode',
            field=models.CharField(blank=True, help_text='Payment Mode (e.g., Bank Account)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='phonepe_processing_mechanism',
            field=models.CharField(blank=True, help_text='Processing Mechanism (e.g., UPI)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='phonepe_product_type',
            field=models.CharField(blank=True, help_text='Product Type (e.g., PhonePe PG)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='phonepe_transaction_date',
            field=models.DateTimeField(blank=True, help_text='PhonePe Transaction Date/Time', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='phonepe_transaction_note',
            field=models.TextField(blank=True, help_text='Transaction Note from PhonePe', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='phonepe_utr',
            field=models.CharField(blank=True, help_text='Unique Transaction Reference from PhonePe', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='phonepe_vpa',
            field=models.CharField(blank=True, help_text='Virtual Payment Address from PhonePe', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='phonepe_merchant_order_id',
            field=models.CharField(blank=True, help_text='Merchant Reference ID', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='phonepe_transaction_id',
            field=models.CharField(blank=True, help_text='PhonePe Transaction ID (OM...)', max_length=100, null=True),
        ),
    ]
