# Generated by Django 5.2.6 on 2025-12-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_order_phonepe_bank_id_order_phonepe_card_network_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variants',
            field=models.JSONField(blank=True, default=dict, help_text='Product variant data with enabled, variants, and combinations'),
        ),
    ]
