# Generated by Django 5.2.6 on 2025-12-16 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_alter_store_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='compare_price',
            new_name='discount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='dimensions',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
        migrations.AddField(
            model_name='product',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('flat', 'Flat'), ('percentage', 'Percentage')], max_length=10, null=True),
        ),
    ]
