# Generated by Django 5.2.6 on 2025-12-16 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_rename_compare_price_product_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Product must be approved by admin before it appears in app/web'),
        ),
    ]
