# Generated by Django 5.2.6 on 2025-12-18 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_product_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_date',
            field=models.DateTimeField(blank=True, help_text='When order is delivered', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='merchant',
            field=models.ForeignKey(blank=True, help_text='Store/vendor for this order', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='ecommerce.store'),
        ),
        migrations.AddField(
            model_name='order',
            name='merchant_ready_date',
            field=models.DateTimeField(blank=True, help_text='When merchant accepts and marks ready', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_date',
            field=models.DateTimeField(blank=True, help_text='When order is picked up', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='reject_reason',
            field=models.TextField(blank=True, help_text='Reason if merchant rejects', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Shipping cost for this order', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Subtotal for this vendor's products", max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
