# Generated by Django 5.2.6 on 2025-12-18 18:40

import django.db.models.deletion
from django.db import migrations, models


def cleanup_invalid_address_ids(apps, schema_editor):
    """
    Clean up corrupted address data in Order table.
    If columns are TextField, we need to clear them before AlterField converts to ForeignKey.
    If columns are already ForeignKey (_id), clean up invalid foreign key references.
    """
    import sys
    from django.db import connection
    
    # Check what columns actually exist in the table
    with connection.cursor() as cursor:
        # Get table schema
        cursor.execute("PRAGMA table_info(ecommerce_order)")
        column_info = cursor.fetchall()
        column_names = {row[1] for row in column_info}  # Set of column names
        
        # Check if shipping_address_id and billing_address_id exist (ForeignKey columns)
        has_shipping_id = 'shipping_address_id' in column_names
        has_billing_id = 'billing_address_id' in column_names
        has_shipping_text = 'shipping_address' in column_names
        has_billing_text = 'billing_address' in column_names
        
        # Clear TextField columns if they exist (before AlterField converts them)
        # Django can't convert text addresses to ForeignKey IDs automatically
        if has_shipping_text:
            print("Clearing shipping_address TextField before converting to ForeignKey...")
            # Try to set to NULL, but if column is NOT NULL, we'll need to handle it differently
            try:
                cursor.execute("UPDATE ecommerce_order SET shipping_address = NULL WHERE shipping_address IS NOT NULL")
                affected = cursor.rowcount
                print(f"Cleared shipping_address TextField for {affected} orders")
            except Exception as e:
                # If setting to NULL fails (e.g., column is NOT NULL), set to empty string
                print(f"Could not set shipping_address to NULL: {e}. Setting to empty string instead.")
                cursor.execute("UPDATE ecommerce_order SET shipping_address = '' WHERE shipping_address IS NOT NULL")
                affected = cursor.rowcount
                print(f"Cleared shipping_address TextField for {affected} orders")
            sys.stdout.flush()
        
        if has_billing_text:
            print("Clearing billing_address TextField before converting to ForeignKey...")
            try:
                cursor.execute("UPDATE ecommerce_order SET billing_address = NULL WHERE billing_address IS NOT NULL")
                affected = cursor.rowcount
                print(f"Cleared billing_address TextField for {affected} orders")
            except Exception as e:
                print(f"Could not set billing_address to NULL: {e}. Setting to empty string instead.")
                cursor.execute("UPDATE ecommerce_order SET billing_address = '' WHERE billing_address IS NOT NULL")
                affected = cursor.rowcount
                print(f"Cleared billing_address TextField for {affected} orders")
            sys.stdout.flush()
        
        # Also clear _id columns if they exist with invalid data
        if has_shipping_id:
            print("Clearing invalid shipping_address_id values...")
            cursor.execute("UPDATE ecommerce_order SET shipping_address_id = NULL WHERE shipping_address_id IS NOT NULL")
            affected = cursor.rowcount
            print(f"Cleared shipping_address_id for {affected} orders")
            sys.stdout.flush()
        
        if has_billing_id:
            print("Clearing invalid billing_address_id values...")
            cursor.execute("UPDATE ecommerce_order SET billing_address_id = NULL WHERE billing_address_id IS NOT NULL")
            affected = cursor.rowcount
            print(f"Cleared billing_address_id for {affected} orders")
            sys.stdout.flush()
        
        # If the _id columns don't exist and we've already handled TextField, we're done
        if not has_shipping_id and not has_billing_id:
            return
        
        # Get all valid address IDs
        Address = apps.get_model('core', 'Address')
        valid_address_ids = set(Address.objects.values_list('id', flat=True))
        
        if not valid_address_ids:
            # No addresses exist, set all to NULL
            if has_shipping_id:
                cursor.execute("UPDATE ecommerce_order SET shipping_address_id = NULL WHERE shipping_address_id IS NOT NULL")
            if has_billing_id:
                cursor.execute("UPDATE ecommerce_order SET billing_address_id = NULL WHERE billing_address_id IS NOT NULL")
            print("No addresses found, set all order address references to NULL")
            sys.stdout.flush()
            return
        
        # Build SELECT query based on what columns exist
        select_cols = ['id']
        if has_shipping_id:
            select_cols.append('shipping_address_id')
        if has_billing_id:
            select_cols.append('billing_address_id')
        
        cursor.execute(f"SELECT {', '.join(select_cols)} FROM ecommerce_order")
        orders = cursor.fetchall()
        
        invalid_shipping = []
        invalid_billing = []
        
        for row in orders:
            order_id = row[0]
            col_idx = 1
            
            # Check shipping_address_id if it exists
            if has_shipping_id:
                shipping_id = row[col_idx]
                col_idx += 1
                if shipping_id is not None:
                    try:
                        shipping_id_int = int(shipping_id) if isinstance(shipping_id, str) else shipping_id
                        if shipping_id_int not in valid_address_ids:
                            invalid_shipping.append(order_id)
                    except (ValueError, TypeError):
                        invalid_shipping.append(order_id)
            
            # Check billing_address_id if it exists
            if has_billing_id:
                billing_id = row[col_idx]
                if billing_id is not None:
                    try:
                        billing_id_int = int(billing_id) if isinstance(billing_id, str) else billing_id
                        if billing_id_int not in valid_address_ids:
                            invalid_billing.append(order_id)
                    except (ValueError, TypeError):
                        invalid_billing.append(order_id)
        
        # Fix invalid shipping_address_id
        if invalid_shipping and has_shipping_id:
            placeholders = ','.join(['?'] * len(invalid_shipping))
            cursor.execute(
                f"UPDATE ecommerce_order SET shipping_address_id = NULL WHERE id IN ({placeholders})",
                invalid_shipping
            )
            print(f"Fixed {len(invalid_shipping)} orders with invalid shipping_address_id")
            sys.stdout.flush()
        
        # Fix invalid billing_address_id
        if invalid_billing and has_billing_id:
            placeholders = ','.join(['?'] * len(invalid_billing))
            cursor.execute(
                f"UPDATE ecommerce_order SET billing_address_id = NULL WHERE id IN ({placeholders})",
                invalid_billing
            )
            print(f"Fixed {len(invalid_billing)} orders with invalid billing_address_id")
            sys.stdout.flush()


def reverse_cleanup(apps, schema_editor):
    """Reverse migration - nothing to reverse for data cleanup"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_user_national_id_document_and_more'),
        ('ecommerce', '0009_order_delivered_date_order_merchant_and_more'),
    ]

    operations = [
        # First, clean up corrupted data
        migrations.RunPython(cleanup_invalid_address_ids, reverse_cleanup),
        # Then, alter the fields
        migrations.AlterField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(blank=True, help_text='Billing address for this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_orders', to='core.address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, help_text='Shipping address for this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_orders', to='core.address'),
        ),
    ]
