# Generated by Django 5.2.6 on 2025-12-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_alter_order_billing_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_variant',
            field=models.CharField(blank=True, help_text='Selected product variant (e.g., "Size:Small,Color:Red")', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
