# Generated by Django 5.2.6 on 2025-12-21 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_orderitem_product_variant_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipdaak_awb_number',
            field=models.CharField(blank=True, help_text='Shipdaak AWB/Tracking number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipdaak_courier_id',
            field=models.IntegerField(blank=True, help_text='Shipdaak courier ID used for shipment', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipdaak_courier_name',
            field=models.CharField(blank=True, help_text='Shipdaak courier name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipdaak_label_url',
            field=models.URLField(blank=True, help_text='Shipdaak shipping label URL', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipdaak_manifest_url',
            field=models.URLField(blank=True, help_text='Shipdaak manifest URL', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipdaak_order_id',
            field=models.IntegerField(blank=True, help_text='Shipdaak order ID', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipdaak_shipment_id',
            field=models.IntegerField(blank=True, help_text='Shipdaak shipment ID', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipdaak_status',
            field=models.CharField(blank=True, help_text='Current Shipdaak shipment status', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='shipdaak_pickup_warehouse_id',
            field=models.IntegerField(blank=True, help_text='Shipdaak pickup warehouse ID', null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='shipdaak_rto_warehouse_id',
            field=models.IntegerField(blank=True, help_text='Shipdaak RTO warehouse ID', null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='shipdaak_warehouse_created_at',
            field=models.DateTimeField(blank=True, help_text='When warehouse was created in Shipdaak', null=True),
        ),
        migrations.CreateModel(
            name='CourierConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_courier_id', models.IntegerField(help_text='Default Shipdaak courier ID for this store')),
                ('default_courier_name', models.CharField(help_text='Default courier name', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this courier configuration is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(help_text='Store for this courier configuration', on_delete=django.db.models.deletion.CASCADE, related_name='courier_config', to='ecommerce.store')),
            ],
            options={
                'verbose_name': 'Courier Configuration',
                'verbose_name_plural': 'Courier Configurations',
                'ordering': ['-created_at'],
            },
        ),
    ]
