# Generated by Django 5.2.6 on 2025-12-21 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_order_shipdaak_awb_number_order_shipdaak_courier_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courierconfiguration',
            options={'ordering': ['priority', 'courier_name'], 'verbose_name': 'Courier Configuration', 'verbose_name_plural': 'Courier Configurations'},
        ),
        migrations.AlterUniqueTogether(
            name='courierconfiguration',
            unique_together={('store', 'courier_id')},
        ),
        migrations.AddField(
            model_name='courierconfiguration',
            name='courier_id',
            field=models.IntegerField(default=1, help_text='Shipdaak courier ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courierconfiguration',
            name='courier_name',
            field=models.CharField(default='Delhivery Surface 2 Kg', help_text='Courier name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courierconfiguration',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Default courier for this store'),
        ),
        migrations.AddField(
            model_name='courierconfiguration',
            name='priority',
            field=models.IntegerField(default=0, help_text='Priority order (lower = higher priority)'),
        ),
        migrations.AlterField(
            model_name='courierconfiguration',
            name='store',
            field=models.ForeignKey(help_text='Store for this courier configuration', on_delete=django.db.models.deletion.CASCADE, related_name='courier_configs', to='ecommerce.store'),
        ),
        migrations.RemoveField(
            model_name='courierconfiguration',
            name='default_courier_id',
        ),
        migrations.RemoveField(
            model_name='courierconfiguration',
            name='default_courier_name',
        ),
    ]
