# Generated by Django 5.2.6 on 2025-12-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0013_alter_courierconfiguration_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalCourier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier_id', models.IntegerField(help_text='Shipdaak courier ID', unique=True)),
                ('courier_name', models.CharField(help_text='Courier name', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this courier is active globally')),
                ('priority', models.IntegerField(default=0, help_text='Priority order (lower = higher priority)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Global Courier',
                'verbose_name_plural': 'Global Couriers',
                'ordering': ['priority', 'courier_name'],
            },
        ),
        migrations.DeleteModel(
            name='CourierConfiguration',
        ),
    ]
