# Generated by Django 5.2.6 on 2025-12-22 18:02

from django.db import migrations, models


def migrate_courier_data(apps, schema_editor):
    """Migrate unique couriers from CourierConfiguration to GlobalCourier"""
    CourierConfiguration = apps.get_model('ecommerce', 'CourierConfiguration')
    GlobalCourier = apps.get_model('ecommerce', 'GlobalCourier')
    
    # Dictionary to track unique couriers and their highest priority
    courier_map = {}
    
    # Collect all unique couriers from all stores
    for config in CourierConfiguration.objects.all():
        courier_id = config.courier_id
        if courier_id not in courier_map:
            courier_map[courier_id] = {
                'courier_id': courier_id,
                'courier_name': config.courier_name,
                'priority': config.priority,
                'is_active': config.is_active,
            }
        else:
            # Use the highest priority (lowest number) if multiple stores have same courier
            if config.priority < courier_map[courier_id]['priority']:
                courier_map[courier_id]['priority'] = config.priority
            # If any store has it active, keep it active
            if config.is_active:
                courier_map[courier_id]['is_active'] = True
    
    # Create GlobalCourier entries
    for courier_data in courier_map.values():
        GlobalCourier.objects.create(
            courier_id=courier_data['courier_id'],
            courier_name=courier_data['courier_name'],
            priority=courier_data['priority'],
            is_active=courier_data['is_active'],
        )


def reverse_migrate_courier_data(apps, schema_editor):
    """Reverse migration - this would be complex, so we'll just clear GlobalCourier"""
    GlobalCourier = apps.get_model('ecommerce', 'GlobalCourier')
    GlobalCourier.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0013_alter_courierconfiguration_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalCourier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier_id', models.IntegerField(help_text='Shipdaak courier ID', unique=True)),
                ('courier_name', models.CharField(help_text='Courier name', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this courier is active globally')),
                ('priority', models.IntegerField(default=0, help_text='Priority order (lower = higher priority)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Global Courier',
                'verbose_name_plural': 'Global Couriers',
                'ordering': ['priority', 'courier_name'],
            },
        ),
        migrations.RunPython(migrate_courier_data, reverse_migrate_courier_data),
        migrations.DeleteModel(
            name='CourierConfiguration',
        ),
    ]
