# Generated by Django 5.2.6 on 2025-12-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_globalcourier_delete_courierconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='package_breadth',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Package breadth in cm', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='package_height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Package height in cm', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='package_length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Package length in cm', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='package_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Package weight in grams', max_digits=8, null=True),
        ),
    ]
