# Generated by Django 5.2.6 on 2025-12-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0015_order_package_breadth_order_package_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='commission_processed',
            field=models.BooleanField(default=False, help_text='Whether commission has been processed for this order'),
        ),
    ]
