# Generated by Django 5.2.6 on 2025-12-23 12:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0016_order_commission_processed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('bank_account_number', models.CharField(help_text='Bank account number', max_length=50)),
                ('bank_ifsc', models.CharField(help_text='Bank IFSC code', max_length=20)),
                ('bank_name', models.CharField(help_text='Bank name', max_length=100)),
                ('account_holder_name', models.CharField(help_text='Account holder name', max_length=100)),
                ('utr', models.CharField(blank=True, help_text='UTR from withdrawal processing', max_length=100, null=True)),
                ('bank_id', models.CharField(blank=True, help_text='Bank ID if processed via PhonePe', max_length=20, null=True)),
                ('vpa', models.CharField(blank=True, help_text='VPA if processed via PhonePe', max_length=100, null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if status is rejected', null=True)),
                ('processed_at', models.DateTimeField(blank=True, help_text='When withdrawal was processed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(limit_choices_to={'is_merchant': True}, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('commission', 'Commission'), ('withdrawal', 'Withdrawal Request'), ('withdrawal_processed', 'Withdrawal Processed'), ('phonepe_payment', 'PhonePe Payment'), ('payout', 'Merchant Payout')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Transaction description')),
                ('utr', models.CharField(blank=True, help_text='Unique Transaction Reference (UTR) for PhonePe transactions', max_length=100, null=True)),
                ('bank_id', models.CharField(blank=True, help_text='Bank ID for PhonePe transactions', max_length=20, null=True)),
                ('vpa', models.CharField(blank=True, help_text='Virtual Payment Address (VPA) for PhonePe transactions', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_order', models.ForeignKey(blank=True, help_text='Related order for commission/payout/phonepe transactions', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='ecommerce.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('related_withdrawal', models.ForeignKey(blank=True, help_text='Related withdrawal for withdrawal transactions', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='ecommerce.withdrawal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='withdrawal',
            index=models.Index(fields=['merchant', '-created_at'], name='ecommerce_w_merchan_13a8be_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawal',
            index=models.Index(fields=['status', '-created_at'], name='ecommerce_w_status_23699b_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', '-created_at'], name='ecommerce_t_user_id_77b486_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type', '-created_at'], name='ecommerce_t_transac_084f0a_idx'),
        ),
    ]
