# Generated by Django 5.2.6 on 2025-12-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0017_withdrawal_transaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('online', 'Online Payment'), ('phonepe', 'PhonePe Payment')], default='cod', max_length=10),
        ),
    ]
