# Generated by Django 5.2.6 on 2025-12-27 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0018_alter_order_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='phonepe_bank_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phonepe_card_network',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phonepe_instrument_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phonepe_merchant_order_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phonepe_order_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phonepe_payment_mode',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phonepe_processing_mechanism',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phonepe_product_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phonepe_transaction_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phonepe_transaction_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phonepe_transaction_note',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phonepe_utr',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phonepe_vpa',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
