# Generated by Django 5.2.6 on 2025-12-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0019_remove_order_phonepe_bank_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Banner image', upload_to='banners/')),
                ('title', models.CharField(help_text='Banner title', max_length=200)),
                ('url', models.URLField(blank=True, help_text='URL to navigate when banner is clicked', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this banner is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Popup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Popup image', upload_to='popups/')),
                ('title', models.CharField(help_text='Popup title', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this popup is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
