# Generated by Django 5.2.6 on 2025-12-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0020_banner_popup'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='item_code',
            field=models.CharField(blank=True, help_text='Auto-generated product code (e.g., PSB1, PSB2)', max_length=50, null=True, unique=True),
        ),
    ]
