# Generated by Django 5.2.6 on 2026-01-07 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0026_merchant_payment_setting'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='merchantpaymentsetting',
            new_name='ecommerce_m_user_id_3bcbaf_idx',
            old_name='ecommerce_m_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='merchantpaymentsetting',
            new_name='ecommerce_m_status_ca5109_idx',
            old_name='ecommerce_m_status_c_idx',
        ),
    ]
