# Generated by Django 5.2.6 on 2026-01-19 12:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0031_shipping_charge_history_add_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingchargehistory',
            name='shipping_charge',
            field=models.DecimalField(decimal_places=2, help_text='Shipping charge amount (courier_rate + commission)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
