# Generated by Django 5.2.6 on 2026-01-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0032_alter_shippingchargehistory_shipping_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawal',
            name='account_holder_name',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='bank_account_number',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='bank_id',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='bank_ifsc',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='processed_at',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='utr',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='vpa',
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
