# Generated by Django 5.2.6 on 2026-01-25 09:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_supersetting_travel_ticket_percentage_and_more'),
        ('ecommerce', '0036_orderitem_actual_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawal',
            name='payment_setting',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='merchant',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Selling price with commission applied', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.DeleteModel(
            name='MerchantPaymentSetting',
        ),
        migrations.DeleteModel(
            name='Withdrawal',
        ),
    ]
