# Generated by Django 5.2.6 on 2025-11-06 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackComplain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('feedback', 'Feedback'), ('complain', 'Complain')], default='feedback', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_complains', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback/Complain',
                'verbose_name_plural': 'Feedbacks/Complains',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackComplainReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin_reply', models.BooleanField(default=False)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feedback_complain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='shared.feedbackcomplain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_replies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback/Complain Reply',
                'verbose_name_plural': 'Feedback/Complain Replies',
                'ordering': ['created_at'],
            },
        ),
    ]
